name: Push Policy Templates
on: [push]

env:
  FLEXERA_PROJECT_ID: 138205

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install fpt
        run: |
          curl -s https://binaries.rightscale.com/rsbin/fpt/v1/fpt-linux-amd64.tgz -o fpt.tgz
          tar -zxf fpt.tgz
          sudo cp ./fpt/fpt /usr/local/bin/fpt
          sudo chmod +x /usr/local/bin/fpt
          fpt --version

      - name: Configure fpt
        run: |
          cat <<EOF> ~/.fpt.yml
          login:
            accounts:
              "${{ env.FLEXERA_PROJECT_ID }}":
                flexera: true
                host: governance-3.rightscale.com
                id: ${{ env.FLEXERA_PROJECT_ID }}
                refresh_token: ${{ secrets.FLEXERA_REFRESH_TOKEN }}
            default_account: "${{ env.FLEXERA_PROJECT_ID }}"
          update:
            check: true
          EOF

      - name: Upload Policy Templates
        run: |
          for pt in `find . -name *.pt`; do
            fpt -a ${{ env.FLEXERA_PROJECT_ID }} upload $pt
          done
